from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Listing(models.Model):
   id = ...
   listing_title = ...
   description = ...
   min_price = ...
   image = ...
   category = ...
   user_id = ...

# class bids():
# class comments():u
